# Generated by Django 5.2.8 on 2025-11-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_customer_address_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='adres',
        ),
    ]
